name: Rust actions

on:
  pull_request:
    branches:
      - 'main'

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SDL2 dev
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev
      
      - name: Lint (clippy)
        run: cargo clippy --all-targets --all-features
      
      - name: Format
        run: cargo fmt --all -- --check

      - name: Test
        run: cargo test --all-features